export const map = [
    { id: 'excelsior',
        x: 60, y: 60,
        'title': 'Beta Thymine, Excelsior Station',
        'connects': ['haliax'],
        'description': 'A tiny backwater, avoid here if possible. Hard to reach, exciting to leave.',
        'items': [
            {name: 'food', quantity: 15,},
            {name: 'medicine', quantity: 24},
            {name: 'luxury', quantity: 6},
        ],
    },
    {id: 'haliax',
    x: 120, y: 120,
        'title': 'Ganymede Prime, Haliax Station',
        'connects': ['excelsior','europa', 'drone'],
        'description': 'A place, things happen here.',
        'items': [
            {name: 'food', quantity: 5,},
            {name: 'medicine', quantity: 14},
            {name: 'luxury', quantity: 22},
        ],
    },
    {id: 'europa',
    x: 60, y: 180,
        'title': 'Echidna 4317, Europa Station',
        'connects': ['haliax','drone'],
        'description': 'Beautiful, elegant, expensive.',
        'items': [
            {name: 'food', quantity: 23,},
            {name: 'medicine', quantity: 9},
            {name: 'luxury', quantity: 21},
        ],
    },
    {id: 'drone',
    x: 140, y: 240,
        'title': 'Eldrazi Minor, Drone Station',
        'connects': ['europa', 'haliax'],
        'description': 'Scary monsters dwell on this station\'s neighboring planet.',
        'items': [
            {name: 'food', quantity: 11,},
            {name: 'medicine', quantity: 7},
            {name: 'luxury', quantity: 10},
        ],
    }
]
